pdf:
	python main.py
	pdflatex --shell-escape Riley-Salladay.tex
	xdg-open Riley-Salladay.pdf
view:
	xdg-open Riley-Salladay.pdf
v:
	xdg-open Riley-Salladay.pdf
cleantmp:
	rm -rf '__pycache__' 'auto' 'desktop.ini' \
	'abc.output' 'texput.log' 'shEsc.tmp' \
	'main.log' 'main.aux' 'main.toc' 'main.out' 'main.idx' 'main.ilg' 'main.vrb' 'main.snm' 'main.nav' \
	'main.py.err' 'main.py.out' 'latex.py' 'main.pytxcode' \
	'makefile.old' 'missfont.log' 'traceback.txt'
c:
	make cleantmp
