run:
	python main.py Japan
	xdg-open cccs-japan.html &

	python main.py China
	xdg-open cccs-china.html &

	python main.py South Korea
	xdg-open cccs-south-korea.html

	python main.py India
	xdg-open cccs-india.html

	python main.py Malaysia
	xdg-open cccs-malaysia.html


