run:
	python main.py Nepal
	xdg-open cccs-nepal.html

	python main.py India
	xdg-open cccs-india.html

	python main.py Pakistan
	xdg-open cccs-pakistan.html

	python main.py Japan
	xdg-open cccs-japan.html &

	python main.py South Korea
	xdg-open cccs-south-korea.html

	python main.py China
	xdg-open cccs-china.html &

	python main.py Vietnam
	xdg-open cccs-vietnam.html

	python main.py Thailand
	xdg-open cccs-thailand.html

	python main.py Malaysia
	xdg-open cccs-malaysia.html

	python main.py Indonesia
	xdg-open cccs-indonesia.html &

